# Generated by Django 5.2.4 on 2025-07-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='alt_text',
            field=models.CharField(default='Portfolio', max_length=255),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
