# Generated by Django 5.2.4 on 2025-07-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='facebook',
            new_name='LinkdIn',
        ),
        migrations.RemoveField(
            model_name='about',
            name='tiktok',
        ),
        migrations.AddField(
            model_name='about',
            name='x_twitter',
            field=models.URLField(blank=True, verbose_name='X (Twitter)'),
        ),
    ]
