# Generated by Django 5.2.4 on 2025-07-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_facebook_about_linkdin_remove_about_tiktok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='cta_button_text',
            field=models.CharField(default='More About Me', max_length=100),
        ),
    ]
