# Generated by Django 5.2.4 on 2025-07-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_about_cta_button_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='morebio',
            field=models.TextField(default='More About Me'),
        ),
    ]
