# Generated by Django 5.2.4 on 2025-07-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_contactinfo_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
